name: Run Daily Stock Analysis

on:
  workflow_dispatch: # 手動実行を許可
  schedule:
    # 毎日AM 9:00 (JST) に実行 (UTCでは 0:00)
    - cron: '0 7 * * *'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3' # requirements.txtと互換性のあるバージョンを指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run stock analysis script
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: python GetStockData_01_9.py

